apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: ClickHouse
    type: clickhouse
    access: proxy
    url: http://clickhouse:8123
    user: signalbeam
    database: signalbeam
    jsonData:
      username: signalbeam
    secureJsonData:
      password: signalbeam_password
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true